runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /dist
  static_dir: dist

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

skip_files:
- ^(node_modules/.*)
- ^(src/js/.*)
